os: unstable
image: Visual Studio 2015

environment:
  RUST_BACKTRACE: 1
  matrix:
    - PLATFORM: x64
      NODEJS_VERSION: "8"
      RUST_TOOLCHAIN: stable-x86_64-pc-windows-msvc
    - PLATFORM: x64
      NODEJS_VERSION: "10"
      RUST_TOOLCHAIN: stable-x86_64-pc-windows-msvc
    - PLATFORM: x64
      NODEJS_VERSION: "10"
      RUST_TOOLCHAIN: beta-x86_64-pc-windows-msvc
    - PLATFORM: x64
      NODEJS_VERSION: "10"
      RUST_TOOLCHAIN: nightly-x86_64-pc-windows-msvc
    - PLATFORM: x64
      NODEJS_VERSION: "12"
      RUST_TOOLCHAIN: stable-x86_64-pc-windows-msvc
    - PLATFORM: x64
      NODEJS_VERSION: "12"
      RUST_TOOLCHAIN: beta-x86_64-pc-windows-msvc
    - PLATFORM: x64
      NODEJS_VERSION: "12"
      RUST_TOOLCHAIN: nightly-x86_64-pc-windows-msvc

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:PLATFORM
  - npm config set msvs_version 2015
  - node -e "console.log(process.argv[0], process.arch, process.versions)"
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y --default-toolchain %RUST_TOOLCHAIN%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup show
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --release

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
