[package]
name = "neon-runtime"
version = "0.3.3"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "Bindings to the Node.js native addon API, used by the Neon implementation."
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"

[dependencies]
cfg-if = "0.1.9"
neon-sys = { version = "=0.3.3", path = "../neon-sys", optional = true }
nodejs-sys = { version = "0.2.0", optional = true }
